//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace fls.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Album> Albums { get; set; }
        public virtual DbSet<Custom> Customs { get; set; }
        public virtual DbSet<InvCode> InvCodes { get; set; }
        public virtual DbSet<Photo> Photos { get; set; }
        public virtual DbSet<Studio> Studios { get; set; }
        public virtual DbSet<Type> Types { get; set; }
    
        public virtual int newAlbumID()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("newAlbumID");
        }
    }
}
